export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Provider from "@/app/_trpc/Provider"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
