export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};
import { cn } from '@/lib/utils';
import Provider from '@/app/_trpc/Provider';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
export const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
